displayName=Autumn Garden
author=Hexi Luibh
support=https://github.com/Hexi-Luibh/autumn-garden
description=An adaptation of Majesty373's Spring garden plugin to help with the Sorceress' Autumn Garden
tags=Sorceress, autumn, garden, thieving, skilling
plugins=com.autumngarden.AutumnGardenPlugin
build=standard
